# Generated by Django 4.2.21 on 2025-05-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
